add lived not arrogant
v-for-vasiliev/GarageMems pull request #9
Opened 2021-11-29 11:15 UTC by DanBykov

<img width="513" alt="lived_not_arrogant" src="https://user-images.githubusercontent.com/2178893/143858363-5f266911-1185-47be-ab06-2fddc425daa6.png">

2022-10-07 23:08 UTC, v-for-vasiliev requested changes
Фон картинки нестандартный, сейчас все скинут с разным фоном и будут босхетти мемы.

2022-10-07 23:08 UTC, v-for-vasiliev commented
переделывай!

2022-10-08 00:16 UTC, DanBykov commented
Это дефолтный цвет темной темы. Любой цвет из доступных в настройках подходит, т.к. может повторяться много раз. Ты предлагаешь мне каждый раз цвет моего фона фотошопить? Я тебе не дизайнер

2022-10-08 00:32 UTC, v-for-vasiliev approved these changes

2022-10-08 00:32 UTC, merged